### PR TITLE
Fix stout compilation error.

### LINKED ISSUE #156: Error when building `stout-collator`: `trappist_config` is not defined
Caused by #148; see https://github.com/paritytech/trappist/pull/148#discussion_r1171272319

### PR DESCRIPTION
**Pull request by hbulgarini**
This PR addresses the compilation issue created in the PR #148.

It also adds some enhancements as creating the `stout-collator` instead of having it to create it manually.

NOTE: For some reason, zombienet is not able to generate and parse the chain specs, but it is working when i generate it manually. I suspect something is happening with zombienet (i have heard others having different issues)

Closes #156

### CODE REVIEW

**Comment by hbulgarini** [comment]
> Trappist id has changed but we forgot to change it in the hrmp_channels too.

It was so obvious and so hard to see!

**Review by stiiifff — APPROVED** [review]

**Comment by stiiifff** [comment]
Good job, thanks @hbulgarini. LGTM
